routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::any('wechat', [\App\Http\Controllers\WeChatController::class, 'serve']);
Route::get('/wechat/qrcode', 'App\Http\Controllers\WeChatController@getQRCode');
Route::any('/wechat/upload', 'App\Http\Controllers\WeChatController@upload');
Route::any('/wechat/alist', 'App\Http\Controllers\WeChatController@alist');
Route::any('/wechat/draft', 'App\Http\Controllers\WeChatController@draft');
Route::any('/wechat/publish', 'App\Http\Controllers\WeChatController@publish');

Route::middleware('splade')->group(function () {
    Route::spladeWithVueBridge();
    Route::spladePasswordConfirmation();
    Route::spladeTable();
    Route::spladeUploads();

    Route::middleware(['auth', 'master', 'verified'])->group(function () {
        Route::get('/dashboard', 'App\Http\Controllers\DashboardController@index')->name('dashboard.index');
        Route::patch('/dashboard', 'App\Http\Controllers\DashboardController@update')->name('dashboard.update');
        Route::get('/dashboard/setting', 'App\Http\Controllers\DashboardController@setting')->name('dashboard.setting');
        Route::get('/dashboard/storage', 'App\Http\Controllers\DashboardController@storage')->name('dashboard.storage');
        Route::get('/dashboard/socialite', 'App\Http\Controllers\DashboardController@socialite')->name('dashboard.socialite');
        Route::get('/dashboard/master', 'App\Http\Controllers\DashboardController@master')->name('dashboard.master');
        Route::get('/dashboard/mail', 'App\Http\Controllers\DashboardController@mail')->name('dashboard.mail');
        Route::get('/dashboard/secure', 'App\Http\Controllers\DashboardController@secure')->name('dashboard.secure');
        Route::get('/dashboard/scout', 'App\Http\Controllers\DashboardController@scout')->name('dashboard.scout');
        Route::get('/dashboard/background/image', 'App\Http\Controllers\DashboardController@bgImage')->name('dashboard.background.image');
        Route::get('/dashboard/background/video', 'App\Http\Controllers\DashboardController@bgVideo')->name('dashboard.background.video');

        Route::resource('posts', \App\Http\Controllers\PostController::class)->except(['show']);
        Route::resource('categories', \App\Http\Controllers\CategoryController::class)->except(['show']);
        Route::get('/tags', 'App\Http\Controllers\TagController@index')->name('tags.index');
        Route::get('/tags/search', 'App\Http\Controllers\TagController@search')->name('tags.search');
        Route::post('/tags', 'App\Http\Controllers\TagController@store')->name('tags.store');
        Route::post('/posts/{post}/tags', 'App\Http\Controllers\TagController@createPostsTag')->name('posts.tags.store');
        Route::get('/posts/{post}/tags', 'App\Http\Controllers\TagController@getPostsTag')->name('posts.tags.index');
        Route::delete('/posts/{post}/tags', 'App\Http\Controllers\TagController@destroyPostsTag')->name('posts.tags.destroy');
        Route::resource('users', \App\Http\Controllers\UserController::class);
        Route::resource('comments', \App\Http\Controllers\CommentController::class)->except(['store']);
        Route::get('/posts/{post}/comments', 'App\Http\Controllers\PostController@comment')->name('posts.comments');
    });

    Route::middleware('uvcount')->group(function () {
        Route::get('/', 'App\Http\Controllers\HomeController@index')->name('home');
        Route::get('/tag/{name?}', 'App\Http\Controllers\HomeController@tag')->name('tag');
        Route::get('/timeline/{yearMonth?}', 'App\Http\Controllers\HomeController@timeline')
            ->where('yearMonth', '(20\d{2}(0[1-9]|1[0-2])|\d{4}(0?[1-9]|1[0-2]))')
            ->name('timeline');
        Route::get('/getPostsByDate/{date}', 'App\Http\Controllers\HomeController@getPostsByDate')->name('getPostsByDate');
        Route::get('/posts/{post:slug}', 'App\Http\Controllers\PostController@show')->name('posts.show');
        Route::get('/categories/{category:slug}', 'App\Http\Controllers\CategoryController@show')->name('categories.show');
        Route::get('/search', 'App\Http\Controllers\HomeController@search')->name('search');
        Route::post('/search', 'App\Http\Controllers\HomeController@searchResult')->name('search.result');
        Route::get('/comments/post/{post:ulid}', 'App\Http\Controllers\CommentController@post')->name('comments.post');
        Route::get('/is_login', function () {
            if (auth()->check()) {
                return response()->json(['code' => 200, 'data' => auth()->user()]);
            } else {
                return response()->json(['code' => 401, 'message' => 'Unauthorized.']);
            }
        });
    });

    Route::middleware(['auth', 'verified'])->group(function () {
        Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
        Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
        Route::post('/comments', 'App\Http\Controllers\CommentController@store')->name('comments.store');
        Route::post('/upload/video', 'App\Http\Controllers\UploadController@video')->name('upload.video');
        Route::post('/upload/image', 'App\Http\Controllers\UploadController@image')->name('upload.image');
        Route::post('/upload/file', 'App\Http\Controllers\UploadController@file')->name('upload.file');
        Route::post('/upload/check_exists', 'App\Http\Controllers\UploadController@checkExists')->name('upload.check_exists');
    });

    Route::get('/install', 'App\Http\Controllers\InstallController@index')->name('install.index');
    Route::get('/install/settings/{locale}', 'App\Http\Controllers\InstallController@settings')->name('install.settings');
    Route::post('/install/check/{locale}', 'App\Http\Controllers\InstallController@check')->name('install.check');
    Route::get('/install/create/{locale}', 'App\Http\Controllers\InstallController@create')->name('install.create');
    Route::post('/install/install/{locale}', 'App\Http\Controllers\InstallController@install')->name('install.install');
    Route::get('/install/finish/{locale}', 'App\Http\Controllers\InstallController@finish')->name('install.finish');
    Route::get('/select-locale/{locale}', function ($locale) {
        \Illuminate\Support\Facades\Session::put('locale', $locale);
        return redirect()->back();
    })->name('select-locale');

    require __DIR__.'/auth.php';
});

app/Http/Controllers/InstallController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Artisan;
use App\Http\Requests\InstallDatabaseRequest;
use App\Http\Requests\InstallUserRequest;
use App\Services\EnvService;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;

class InstallController extends Controller
{
    public function __construct()
    {
        $this->middleware('install')->except(['finish']);
    }

    public function index()
    {
        $locale = Session::get('locale', env('APP_LOCALE'));
        App::setLocale($locale);
        $locales = EnvService::getEnvLocale();
        Artisan::call('key:generate', ['--force' => true]);
        Artisan::call('storage:link', ['--force' => true]);
        Artisan::call('optimize:clear');
        return view('install.index', compact('locale', 'locales'));
    }

    public function settings($locale)
    {
        App::setLocale($locale);
        return view('install.settings', compact('locale'));
    }

    public function check(InstallDatabaseRequest $request, $locale)
    {
        App::setLocale($locale);
        $request->validated();
        try {
            $dsn = sprintf('mysql:host=%s;port=%s;dbname=%s', $request->input('database.host'), $request->input('database.port'), $request->input('database.name'));
            new \PDO($dsn, $request->input('database.username'), $request->input('database.password'));
            EnvService::updateEnv('APP_NAME', $request->input('website.name'));
            EnvService::updateEnv('APP_URL', $request->input('website.address'));
            EnvService::updateEnv('APP_LOCALE', $locale);
            EnvService::updateEnv('DB_HOST', $request->input('database.host'));
            EnvService::updateEnv('DB_PORT', $request->input('database.port'));
            EnvService::updateEnv('DB_DATABASE', $request->input('database.name'));
            EnvService::updateEnv('DB_USERNAME', $request->input('database.username'));
            EnvService::updateEnv('DB_PASSWORD', $request->input('database.password'));
            return redirect()->route('install.create', ['locale' => $locale]);
        } catch (\PDOException $e) {
            throw ValidationException::withMessages([
                'database.host' => trans('The database connection failed, please check that the database is configured correctly.'),
            ]);
        }
    }

    public function create($locale)
    {
        App::setLocale($locale);
        if (env('APP_NAME') && env('APP_URL') && env('DB_HOST') && env('DB_PORT') && env('DB_DATABASE') && env('DB_USERNAME') && env('DB_PASSWORD')) {
            try {
                $dsn = sprintf('mysql:host=%s;port=%s;dbname=%s', env('DB_HOST'), env('DB_PORT'), env('DB_DATABASE'));
                new \PDO($dsn, env('DB_USERNAME'), env('DB_PASSWORD'));
                return view('install.create', compact('locale'));
            } catch (\PDOException $e) {
                return redirect()->route('install.index');
            }
        } else {
            return redirect()->route('install.index')->with('locale', $locale);
        }
    }

    public function install(InstallUserRequest $request, $locale)
    {
        App::setLocale($locale);
        $request->validated();
        if (env('APP_NAME') && env('APP_URL') && env('DB_HOST') && env('DB_PORT') && env('DB_DATABASE') && env('DB_USERNAME') && env('DB_PASSWORD')) {
            try {
                $dsn = sprintf('mysql:host=%s;port=%s;dbname=%s', env('DB_HOST'), env('DB_PORT'), env('DB_DATABASE'));
                new \PDO($dsn, env('DB_USERNAME'), env('DB_PASSWORD'));
                EnvService::updateEnv('WEBMASTER_NAME', $request->input('name'));
                EnvService::updateEnv('WEBMASTER_EMAIL', $request->input('email'));
                Artisan::call('migrate:fresh', ['--force' => true]);
                \App\Models\User::create([
                    'name' => $request->name,
                    'email' => $request->email,
                    'password' => Hash::make($request->password),
                    'email_verified_at' => now(),
                ]);
                \App\Models\Category::create([
                    'title' => trans('install.first_category_name'),
                    'slug' => trans('install.first_category_slug'),
                    'parent_id' => null,
                    'description' => trans('install.first_category_description')
                ]);
                $firstUlid = Str::ulid();
                \App\Models\Post::create([
                    'ulid' => $firstUlid,
                    'title' => trans('install.first_article_title'),
                    'slug' => trans('install.first_article_slug'),
                    'content' => trans('install.first_article_content'),
                    'image' => '/storage/images/660200782b63f73c4ae3fa42773deeea.jpg',
                    'background_image' => 1,
                    'published' => 1,
                    'user_id' => 1,
                    'category_id' => 1,
                    'views' => 0,
                    'meta_description' => trans('install.first_article_description'),
                    'meta_keywords' => env('APP_KEYWORDS'),
                    'published_at' => date('Y-m-d H:i:s', strtotime('-10 minute'))
                ]);
                \App\Models\Post::create([
                    'ulid' => Str::ulid(),
                    'title' => trans('install.second_article_title'),
                    'slug' => trans('install.second_article_slug'),
                    'content' => trans('install.second_article_content'),
                    'image' => '',
                    'background_image' => 0,
                    'published' => 1,
                    'user_id' => 1,
                    'category_id' => 1,
                    'views' => 0,
                    'meta_description' => trans('install.second_article_description'),
                    'meta_keywords' => env('APP_KEYWORDS'),
                    'published_at' => date('Y-m-d H:i:s', strtotime('-5 minute'))
                ]);
                \App\Models\Post::create([
                    'ulid' => Str::ulid(),
                    'title' => trans('install.third_article_title'),
                    'slug' => trans('install.third_article_slug'),
                    'content' => trans('install.third_article_content'),
                    'image' => '/storage/images/660200782b63f73c4ae3fa42773deeea.jpg',
                    'background_image' => 0,
                    'published' => 1,
                    'user_id' => 1,
                    'category_id' => 1,
                    'views' => 0,
                    'meta_description' => trans('install.third_article_description'),
                    'meta_keywords' => env('APP_KEYWORDS'),
                    'published_at' => date('Y-m-d H:i:s')
                ]);
                \App\Models\Comment::create([
                    'post_id' => $firstUlid,
                    'user_id' => 1,
                    'parent_id' => null,
                    'content' => trans('install.first_comment_content'),
                ]);
                \App\Models\Tag::create([
                    'name' => 'DustinkY',
                    'user_id' => 1,
                ]);
                \App\Models\PostsTag::create([
                    'post_id' => $firstUlid,
                    'tag_id' => 1,
                ]);
                \App\Models\Statistic::create([
                    'total_uv' => 1,
                ]);
                file_put_contents(base_path('install.lock'), 'this system is installed at ' . date('Y-m-d H:i:s'));
                return redirect()->route('install.finish', ['locale' => $locale]);
            } catch (\PDOException $e) {
                return redirect()->route('install.index')->with('locale', $locale);
            }
        }
    }

    public function finish($locale)
    {
        App::setLocale($locale);
        if (env('APP_NAME') && env('APP_URL') && env('DB_HOST') && env('DB_PORT') && env('DB_DATABASE') && env('DB_USERNAME') && env('DB_PASSWORD') && is_file(base_path('install.lock'))) {
            return view('install.finish');
        } else {
            return redirect()->route('install.index');
        }
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/install/create.blade.php
<x-guest-layout>
    @seoTitle(__('DustinkY Blog system installation'))
    <x-install-card step="3">
        <x-splade-form action="{{ route('install.install', ['locale' => $locale]) }}" class="space-y-4">
            <h2 class="font-semibold leading-7 text-lg py-4 px-4 dark:text-gray-200">
                {{ __('Webmaster Info') }}
            </h2>
            <dl class="divide-y divide-gray-100 text-sm leading-6">
                <div class="flex justify-center py-2 px-4">
                    <dt class="font-medium sm:w-64 sm:flex-none sm:pr-6 leading-9 dark:text-gray-200">{{ __('Webmaster Name') }}</dt>
                    <dd class="flex justify-between gap-x-6 sm:flex-auto">
                        <x-splade-input id="name" type="text" name="name" placeholder="{{ __('Please enter the webmaster name') }}" class="w-96" autofocus />
                    </dd>
                </div>
                <div class="flex justify-center py-2 px-4">
                    <dt class="font-medium sm:w-64 sm:flex-none sm:pr-6 leading-9 dark:text-gray-200">{{ __('Webmaster Email') }}</dt>
                    <dd class="flex justify-between gap-x-6 sm:flex-auto">
                        <x-splade-input id="email" type="email" name="email" placeholder="{{ __('Please enter the webmaster email') }}" class="w-96" autofocus />
                    </dd>
                </div>
                <div class="flex justify-center py-2 px-4">
                    <dt class="font-medium sm:w-64 sm:flex-none sm:pr-6 leading-9 dark:text-gray-200">{{ __('Password') }}</dt>
                    <dd class="flex justify-between gap-x-6 sm:flex-auto">
                        <x-splade-input id="password" type="password" name="password" placeholder="{{ __('Please enter your password') }}" class="w-96" autocomplete="new-password" />
                    </dd>
                </div>
                <div class="flex justify-center py-2 px-4">
                    <dt class="font-medium sm:w-64 sm:flex-none sm:pr-6 leading-9 dark:text-gray-200">{{ __('Confirm Password') }}</dt>
                    <dd class="flex justify-between gap-x-6 sm:flex-auto">
                        <x-splade-input id="password_confirmation" type="password" name="password_confirmation" placeholder="{{ __('Please enter your password again') }}" class="w-96" />
                    </dd>
                </div>
            </dl>
            <div class="flex justify-center mt-6 gap-x-3">
                <Link href="{{ route('install.settings', ['locale' => $locale]) }}" class="bg-gray-400 px-4 py-2 rounded-lg text-gray-600 hover:bg-gray-300">{{ __('Take a step back') }}</Link>
                <x-splade-submit class="w-full" :label="__('Take a step forward')" />
            </div>
        </x-splade-form>
    </x-install-card>
</x-guest-layout>

resources/views/install/index.blade.php
<x-guest-layout>
    @seoTitle(__('DustinkY Blog system installation'))
    <x-install-card step="1">
        <div class="leading-10 p-3">
            <div class="flex justify-between">
                <select id="language-select" class="rounded-md bg-opacity-80 focus:ring-green-500 focus:ring-2 ring-1 ring-gray-300 border-0">
                    @foreach($locales as $item)
                        @if($item['code'] == $locale)
                            <option value="{{ $item['code'] }}" selected>{{ $item['name'] }}</option>
                        @else
                            <option value="{{ $item['code'] }}">{{ $item['name'] }}</option>
                        @endif
                    @endforeach
                    <!-- 其他语言选项 -->
                </select>

                <ThemeSwitch class="ml-5 pt-1" />
            </div>
            <h1 class="text-2xl font-semibold text-center py-6 dark:text-white">{{ __('DustinkY Blog system installation protocol') }}</h1>
            {!! trans('install.welcome') !!}
        </div>
        <div class="flex justify-center mt-6 gap-x-3">
            <Link href="{{ route('install.settings', ['locale' => $locale]) }}" class="bg-green-500 px-4 py-2 rounded-md text-white hover:bg-green-400">{{ __('Agree to the agreement and continue') }}</Link>
        </div>
    </x-install-card>
</x-guest-layout>
<x-splade-script>
    document.getElementById('language-select').addEventListener('change', function() {
    var selectedLanguage = this.value;
    window.location.href = '/select-locale/' + selectedLanguage;
    });
</x-splade-script>

resources/views/install/settings.blade.php
<x-guest-layout>
    @seoTitle(__('DustinkY Blog system installation'))
    <x-install-card step="2">
        <x-splade-form action="{{ route('install.check', ['locale' => $locale]) }}" class="space-y-4">
            <h2 class="font-semibold leading-7 text-lg py-4 px-4 dark:text-gray-200">
                {{ __('Basic information of the website') }}
            </h2>
            <dl class="divide-y divide-gray-100 text-sm leading-6">
                <div class="flex justify-center py-2 px-4">
                    <dt class="font-medium sm:w-64 sm:flex-none sm:pr-6 leading-9 dark:text-gray-200">{{ __('Website name') }}</dt>
                    <dd class="flex justify-between gap-x-6 sm:flex-auto">
                        <x-splade-input id="website.name" type="text" name="website.name" placeholder="{{ __('Please enter the website name') }}" class="w-96" autofocus />
                    </dd>
                </div>
                <div class="flex justify-center py-2 px-4">
                    <dt class="font-medium sm:w-64 sm:flex-none sm:pr-6 leading-9 dark:text-gray-200">{{ __('Website address') }}</dt>
                    <dd class="flex justify-between gap-x-6 sm:flex-auto">
                        <x-splade-input id="website.address" type="text" name="website.address" placeholder="{{ __('Please enter the website address') }}" class="w-96" autofocus />
                    </dd>
                </div>
            </dl>
            <h2 class="font-semibold leading-7 text-lg py-4 px-4 dark:text-gray-200">
                {{ __('Database information') }}
            </h2>
    <dl class="divide-y divide-gray-100 text-sm leading-6">
                <div class="flex justify-center py-2 px-4">
                    <dt class="font-medium sm:w-64 sm:flex-none sm:pr-6 leading-9 dark:text-gray-200">{{ __('Database host') }}</dt>
                    <dd class="flex justify-between gap-x-6 sm:flex-auto">
                        <x-splade-input id="database.host" type="text" name="database.host" placeholder="{{ __('Please enter database host') }}" class="w-96" autofocus />
                    </dd>
                </div>
                    <div class="flex justify-center py-2 px-4">
                    <dt class="font-medium sm:w-64 sm:flex-none sm:pr-6 leading-9 dark:text-gray-200">{{ __('Database port') }}</dt>
                        <dd class="flex justify-between gap-x-6 sm:flex-auto">
                            <x-splade-input id="database.port" type="text" name="database.port" placeholder="{{ __('Please enter database port') }}" class="w-96" autofocus />
                        </dd>
                </div>
                <div class="flex justify-center py-2 px-4">
                    <dt class="font-medium sm:w-64 sm:flex-none sm:pr-6 leading-9 dark:text-gray-200">{{ __('Database name') }}</dt>
                    <dd class="flex justify-between gap-x-6 sm:flex-auto">
                        <x-splade-input id="database.name" type="text" name="database.name" placeholder="{{ __('Please enter database name') }}" class="w-96" autofocus />
                    </dd>
                </div>
                <div class="flex justify-center py-2 px-4">
                    <dt class="font-medium sm:w-64 sm:flex-none sm:pr-6 leading-9 dark:text-gray-200">{{ __('Database username') }}</dt>
                    <dd class="flex justify-between gap-x-6 sm:flex-auto">
                        <x-splade-input id="database.username" type="text" name="database.username" placeholder="{{ __('Please enter database username') }}" class="w-96" autofocus />
                    </dd>
                </div>
                <div class="flex justify-center py-2 px-4">
                    <dt class="font-medium sm:w-64 sm:flex-none sm:pr-6 leading-9 dark:text-gray-200">{{ __('Database password') }}</dt>
                    <dd class="flex justify-between gap-x-6 sm:flex-auto">
                        <x-splade-input id="database.password" type="text" name="database.password" placeholder="{{ __('Please enter database password') }}" class="w-96" autofocus />
                    </dd>
                </div>
            </dl>
            <div class="flex justify-center mt-6 gap-x-3">
                <Link href="{{ route('install.index') }}" class="bg-gray-400 px-4 py-2 rounded-lg text-gray-600 hover:bg-gray-300">{{ __('Take a step back') }}</Link>
                <x-splade-submit class="w-full" :label="__('Detect database connections and install the system')" />
            </div>
        </x-splade-form>
    </x-install-card>
</x-guest-layout>