routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::any('wechat', [\App\Http\Controllers\WeChatController::class, 'serve']);
Route::get('/wechat/qrcode', 'App\Http\Controllers\WeChatController@getQRCode');
Route::any('/wechat/upload', 'App\Http\Controllers\WeChatController@upload');
Route::any('/wechat/alist', 'App\Http\Controllers\WeChatController@alist');
Route::any('/wechat/draft', 'App\Http\Controllers\WeChatController@draft');
Route::any('/wechat/publish', 'App\Http\Controllers\WeChatController@publish');

Route::middleware('splade')->group(function () {
    Route::spladeWithVueBridge();
    Route::spladePasswordConfirmation();
    Route::spladeTable();
    Route::spladeUploads();

    Route::middleware(['auth', 'master', 'verified'])->group(function () {
        Route::get('/dashboard', 'App\Http\Controllers\DashboardController@index')->name('dashboard.index');
        Route::patch('/dashboard', 'App\Http\Controllers\DashboardController@update')->name('dashboard.update');
        Route::get('/dashboard/setting', 'App\Http\Controllers\DashboardController@setting')->name('dashboard.setting');
        Route::get('/dashboard/storage', 'App\Http\Controllers\DashboardController@storage')->name('dashboard.storage');
        Route::get('/dashboard/socialite', 'App\Http\Controllers\DashboardController@socialite')->name('dashboard.socialite');
        Route::get('/dashboard/master', 'App\Http\Controllers\DashboardController@master')->name('dashboard.master');
        Route::get('/dashboard/mail', 'App\Http\Controllers\DashboardController@mail')->name('dashboard.mail');
        Route::get('/dashboard/secure', 'App\Http\Controllers\DashboardController@secure')->name('dashboard.secure');
        Route::get('/dashboard/scout', 'App\Http\Controllers\DashboardController@scout')->name('dashboard.scout');
        Route::get('/dashboard/background/image', 'App\Http\Controllers\DashboardController@bgImage')->name('dashboard.background.image');
        Route::get('/dashboard/background/video', 'App\Http\Controllers\DashboardController@bgVideo')->name('dashboard.background.video');

        Route::resource('posts', \App\Http\Controllers\PostController::class)->except(['show']);
        Route::resource('categories', \App\Http\Controllers\CategoryController::class)->except(['show']);
        Route::get('/tags', 'App\Http\Controllers\TagController@index')->name('tags.index');
        Route::get('/tags/search', 'App\Http\Controllers\TagController@search')->name('tags.search');
        Route::post('/tags', 'App\Http\Controllers\TagController@store')->name('tags.store');
        Route::post('/posts/{post}/tags', 'App\Http\Controllers\TagController@createPostsTag')->name('posts.tags.store');
        Route::get('/posts/{post}/tags', 'App\Http\Controllers\TagController@getPostsTag')->name('posts.tags.index');
        Route::delete('/posts/{post}/tags', 'App\Http\Controllers\TagController@destroyPostsTag')->name('posts.tags.destroy');
        Route::resource('users', \App\Http\Controllers\UserController::class);
        Route::resource('comments', \App\Http\Controllers\CommentController::class)->except(['store']);
        Route::get('/posts/{post}/comments', 'App\Http\Controllers\PostController@comment')->name('posts.comments');
    });

    Route::middleware('uvcount')->group(function () {
        Route::get('/', 'App\Http\Controllers\HomeController@index')->name('home');
        Route::get('/tag/{name?}', 'App\Http\Controllers\HomeController@tag')->name('tag');
        Route::get('/timeline/{yearMonth?}', 'App\Http\Controllers\HomeController@timeline')
            ->where('yearMonth', '(20\d{2}(0[1-9]|1[0-2])|\d{4}(0?[1-9]|1[0-2]))')
            ->name('timeline');
        Route::get('/getPostsByDate/{date}', 'App\Http\Controllers\HomeController@getPostsByDate')->name('getPostsByDate');
        Route::get('/posts/{post:slug}', 'App\Http\Controllers\PostController@show')->name('posts.show');
        Route::get('/categories/{category:slug}', 'App\Http\Controllers\CategoryController@show')->name('categories.show');
        Route::get('/search', 'App\Http\Controllers\HomeController@search')->name('search');
        Route::post('/search', 'App\Http\Controllers\HomeController@searchResult')->name('search.result');
        Route::get('/comments/post/{post:ulid}', 'App\Http\Controllers\CommentController@post')->name('comments.post');
        Route::get('/is_login', function () {
            if (auth()->check()) {
                return response()->json(['code' => 200, 'data' => auth()->user()]);
            } else {
                return response()->json(['code' => 401, 'message' => 'Unauthorized.']);
            }
        });
    });

    Route::middleware(['auth', 'verified'])->group(function () {
        Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
        Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
        Route::post('/comments', 'App\Http\Controllers\CommentController@store')->name('comments.store');
        Route::post('/upload/video', 'App\Http\Controllers\UploadController@video')->name('upload.video');
        Route::post('/upload/image', 'App\Http\Controllers\UploadController@image')->name('upload.image');
        Route::post('/upload/file', 'App\Http\Controllers\UploadController@file')->name('upload.file');
        Route::post('/upload/check_exists', 'App\Http\Controllers\UploadController@checkExists')->name('upload.check_exists');
    });

    Route::get('/install', 'App\Http\Controllers\InstallController@index')->name('install.index');
    Route::get('/install/settings/{locale}', 'App\Http\Controllers\InstallController@settings')->name('install.settings');
    Route::post('/install/check/{locale}', 'App\Http\Controllers\InstallController@check')->name('install.check');
    Route::get('/install/create/{locale}', 'App\Http\Controllers\InstallController@create')->name('install.create');
    Route::post('/install/install/{locale}', 'App\Http\Controllers\InstallController@install')->name('install.install');
    Route::get('/install/finish/{locale}', 'App\Http\Controllers\InstallController@finish')->name('install.finish');
    Route::get('/select-locale/{locale}', function ($locale) {
        \Illuminate\Support\Facades\Session::put('locale', $locale);
        return redirect()->back();
    })->name('select-locale');

    require __DIR__.'/auth.php';
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class Post extends Model
{
    use HasFactory;
    use Searchable;

    protected $primaryKey = 'ulid';
    protected $keyType = 'string';

    protected $fillable = [
        'ulid',
        'title',
        'slug',
        'content',
        'image',
        'background_image',
        'published',
        'published_at',
        'views',
        'meta_description',
        'meta_keywords',
        'user_id',
        'category_id'
    ];

    protected $casts = [ 'published_at' => 'datetime' ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class, 'post_id');
    }

    public function getImageAttribute($value)
    {
        $backgroundImageArray = json_decode(env('BACKGROUND_IMAGE'), true);
        if (empty($backgroundImageArray)) {
            $defaultImage = '/storage/images/660200782b63f73c4ae3fa42773deeea.jpg';
        } else {
            $defaultImage = $backgroundImageArray[array_rand($backgroundImageArray)]['url'];
        }
        return $value ?: $defaultImage;
    }

    public function searchableAs()
    {
        return 'posts';
    }

    public function shouldBeSearchable()
    {
        return $this->published;
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StorePostRequest;
use App\Http\Requests\UpdatePostRequest;
use App\Models\Post;
use App\Services\CategoryService;
use App\Services\PostService;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use ProtoneMedia\Splade\Facades\SEO;
use ProtoneMedia\Splade\Facades\Toast;
use ProtoneMedia\Splade\SpladeTable;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //获取分页数据
        $posts = Post::orderBy('created_at', 'desc')->paginate(10);
        //渲染视图
        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $ulid = Str::ulid();
        Post::create([
            'ulid' => $ulid,
            'title' => trans('This article was created on') . date('Y-m-d H:i:s'),
            'slug' => Str::uuid(),
            'content' => 'new content',
            'background_image' => false,
            'user_id' => Auth::id(),
            'category_id' => DB::table('categories')->first()->id,
            'views' => 0,
            'meta_description' => env('APP_DESCRIPTION'),
            'meta_keywords' => env('APP_KEYWORDS'),
            'published_at' => date('Y-m-d H:i:s')
        ]);

        Toast::success(trans('Post created successfully!'))->autoDismiss(5);

        return redirect()->route('posts.edit', $ulid);
    }

    public function comment(Post $post)
    {
        return view('posts.comment', [
            'comments' => SpladeTable::for($post->comments()->getQuery())
                ->withGlobalSearch(columns: ['id', 'user.name', 'content'])
                ->column('id', sortable: true)
                ->column('user.name', 'Comment User', sortable: true)
                ->column('content', 'Comment Content', sortable: true)
                ->column('created_at', 'Comment Created At', sortable: true)
                ->column(label: 'Actions')
                ->paginate(15),
            'post' => $post,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StorePostRequest $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(Post $post)
    {
        //判断文章是否发布
        if (!$post->published) {
            abort(404);
        }
        $post->timestamps = false; // 关闭自动更新时间戳
        $post->increment('views');
        $post->with('category', 'user', 'tags');

        $tags = PostService::getPostsTagsJson($post->ulid);

        SEO::openGraphType('article');
        SEO::openGraphTitle($post->title);
        SEO::openGraphUrl(config('app.url').'/posts/'.$post->slug);
        SEO::openGraphImage($post->image);
        SEO::metaByProperty('og:description', $post->meta_description);
        if ($post->background_image && $post->image !== '') {
            \Illuminate\Support\Facades\View::share('BACKGROUND_IMAGE', $post->image);
            \Illuminate\Support\Facades\View::share('BACKGROUND_TYPE', 'image');
        }
        return view('posts.show', compact('post', 'tags'));
    }


    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Post $post)
    {
        $categories = CategoryService::getCategories();
        return view('posts.edit', compact('post', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdatePostRequest $request, Post $post)
    {
        $post->update($request->validated());

        return response()->json($post);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Post $post)
    {
        $post->delete();
        Toast::success(trans('Post deleted successfully!'))->autoDismiss(5);
        return redirect()->route('posts.index');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/posts/comment.blade.php
<x-app-layout>
    @seoTitle(__('Comment Management'))
    <x-slot name="header">
        <div class="flex justify-between items-center">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight dark:text-gray-200">
                {!! trans("List of comments on the article ':title'", ['title' => $post->title]) !!}
            </h2>
        </div>
    </x-slot>

    <div class="py-8">
        <div class="max-w-7xl mx-auto px-4">
            <x-splade-table :for="$comments">
                <x-splade-cell actions>
                    <div class="space-x-2">
                        <Link href="{{ route('posts.show', $item->post) }}"> {{ __('Show Post') }} </Link>
                        <Link class="text-red-600 hover:text-red-400" href="{{ route('comments.destroy', $item->id) }}" method="delete" confirm="{{ __('Dangerous operation, confirm to continue?') }}" confirm-text="{{ __('Are you sure to delete this comment?') }}"> {{ __('Delete') }} </Link>
                    </div>
                </x-splade-cell>
            </x-splade-table>
        </div>
    </div>
</x-app-layout>

resources/views/posts/edit.blade.php
<x-app-layout>
    @seoTitle(__('Post Edit'))
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight dark:text-gray-200">
            {{ __('Post Edit') }}
        </h2>
        <div class="flex justify-between w-full mt-4 dark:text-gray-200">
            <div class="mb-2 flex-grow flex justify-between rounded-lg bg-gray-100 bg-opacity-50 text-black pr-3 pl-3 mr-3 dark:invert">
                <div class="flex-shrink justify-start text-xl leading-8 py-2">
                    {{ route('posts.index') }}/
                </div>
                <div class="flex-grow pr-3 leading-8 -ml-3"
                     x-data="{
                    slug: '{{ $post->slug }}',
                    init() {
                        this.$watch('slug', (value) => {
                            axios.patch('{{ route('posts.update', $post) }}', { slug: value })
                                .then(response => {
                                    console.log(response)
                                })
                        })
                    }
                }"
                >
                    <input type="text" x-model.debounce.3000ms="slug" class="w-full text-xl focus:ring-0 leading-8 border-0 bg-transparent">
                </div>
            </div>
            <div class="flex flex-shrink pr-3 leading-8 py-2"
                x-data="{
                    published_at: '{{ $post->published_at }}',
                    init() {
                        this.$watch('published_at', (value) => {
                            axios.patch('{{ route('posts.update', $post) }}', {
                                published_at: value
                            })
                        })
                    }
                }"
            >
                <label class="mr-2">{{ __('Publish Date') }}</label>
                <input type="datetime-local" name="published_at" x-model.debounce.3000ms="published_at" class="-mt-2 focus:ring-0 outline-none border-0 border-gray-300 px-4 py-3 rounded-md bg-gray-100 bg-opacity-80 text-black dark:invert">
            </div>
            <div class="flex-shrink flex justify-end">
                <div x-data="{
                  published: {{ $post->published }},
                  toggle() {
                    this.published = !this.published;
                    axios.patch('{{ route('posts.update', $post) }}', {
                      published: this.published
                    });
                  },
                  publishedStatus() {
                    return this.published ? `&nbsp;{{ __('Unpublish') }}` : `&nbsp;{{ __('Publish') }}`;
                  }
                }">
                <button x-on:click="toggle()" x-text="publishedStatus()" class="antd icon-publish px-4 py-1 mt-1 leading-8 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-green-600 border border-transparent rounded-lg active:bg-green-600 hover:bg-green-700 focus:outline-none focus:shadow-outline-green" x-bind:class="{ 'icon-unpublish bg-orange-500 hover:bg-orange-400': published }"></button>
                </div>
            </div>
        </div>
    </x-slot>
    <div class="pt-16 pb-6 relative z-0">
        <WangEditor title-value="{{ $post->title }}" content="{{ $post->content }}" url="{{ route('posts.update', $post) }}" uploadImageUrl="{{ route('upload.image') }}" uploadVideoUrl="{{ route('upload.video') }}" checkUrl="{{ route('upload.check_exists') }}" />
        <div class="max-w-7xl mx-auto px-4">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg sm:py-1 lg:px-8 dark:bg-zinc-900 bg-opacity-50 dark:bg-opacity-50 backdrop-blur-sm backdrop-filter">
                <div class="sm:grid sm:grid-cols-12 sm:items-start sm:gap-4 sm:py-3" x-data="{
                    toggle(category_id) {
                        axios.patch('{{ route('posts.update', $post) }}', {
                            category_id: category_id
                        })
                    },
                }">
                    <label for="category_id" class="block font-medium leading-6 text-gray-700 py-4 flex-shrink dark:text-gray-200 sm:pt-1.5">{{ __('Select Category') }}</label>
                    <div class="mt-2 sm:col-span-11 sm:mt-0">
                        <select id="category_id" x-on:change="toggle($event.target.value)" name="category_id" class="pl-3 block w-full focus:ring-0 flex-grow py-2 outline-none border-0 sm:rounded-lg bg-gray-100 bg-opacity-80 text-gray-800 dark:bg-zinc-700 dark:text-gray-300 form-select sm:max-w-6xl">
                            @foreach ($categories as $category)
                                <option value="{{ $category->id }}" {{ $category->id == $post->category_id ? 'selected' : '' }}>
                                    {{ str_repeat('-', $category->depth) }} {{ $category->title }}
                                </option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="sm:grid sm:grid-cols-12 sm:items-start sm:gap-4 sm:py-3" x-data="{
                    meta_keywords: '{{ $post->meta_keywords }}',
                    init() {
                        this.$watch('meta_keywords', (value) => {
                            axios.patch('{{ route('posts.update', $post) }}', {
                                meta_keywords: value
                            })
                        })
                    }
                }"
                >
                    <label for="meta_keywords" class="block font-medium leading-6 text-gray-700 py-4 flex-shrink dark:text-gray-200 sm:pt-1.5">{{ __('Post Keywords') }}</label>
                    <div class="mt-2 sm:col-span-11 sm:mt-0">
                        <input type="text" name="meta_keywords" id="meta_keywords" x-model.debounce.3000ms="meta_keywords" class="block w-full max-w-6xl focus:ring-0 flex-grow py-2 outline-none border-0 sm:rounded-lg bg-gray-100 bg-opacity-80 text-gray-800 dark:bg-zinc-700 dark:text-gray-300">
                    </div>
                </div>
                <div class="sm:grid sm:grid-cols-12 sm:items-start sm:gap-4 sm:py-3" x-data="{
                    meta_description: '{{ $post->meta_description }}',
                    init() {
                        this.$watch('meta_description', (value) => {
                            axios.patch('{{ route('posts.update', $post) }}', {
                                meta_description: value
                            })
                        })
                    }
                }"
                >
                    <label for="meta_description" class="block font-medium leading-6 text-gray-700 py-4 flex-shrink dark:text-gray-200 sm:pt-1.5">{{ __('Post Description') }}</label>
                    <div class="mt-2 sm:col-span-11 sm:mt-0">
                        <textarea id="about" name="about" x-model.debounce.3000ms="meta_description" rows="3" class="block w-full max-w-6xl focus:ring-0 flex-grow py-2 outline-none border-0 sm:rounded-lg bg-gray-100 bg-opacity-80 text-gray-800 dark:bg-zinc-700 dark:text-gray-300"></textarea>
                    </div>
                </div>
                <div class="sm:grid sm:grid-cols-12 sm:items-start sm:gap-4 sm:py-3">
                    <label class="block font-medium leading-6 text-gray-700 py-4 flex-shrink dark:text-gray-200 sm:pt-1.5">{{ __('Post Thumbnail') }}</label>
                    <div class="sm:col-span-11 sm:mt-0">
                        <UploadImage check-url="{{ route('upload.check_exists') }}" upload-url="{{ route('upload.image') }}" input-key="image" button-text="{{ __('Post Image') }}" save-url="{{ route('posts.update', $post) }}" image-url="{{ $post->image }}"/>
                    </div>
                </div>
                <div class="sm:grid sm:grid-cols-12 sm:items-start sm:gap-4 sm:py-3">
                    <label class="block font-medium leading-6 text-gray-700 py-4 flex-shrink dark:text-gray-200 sm:pt-1.5">{{ __('Background Image') }}</label>
                    <div class="sm:col-span-11 sm:mt-0 py-2">
                        <Switch text="{{ __('yes|no') }}" :value="{{ $post->background_image }}" input-key="background_image" save-url="{{ route('posts.update', $post) }}" />
                    </div>
                </div>


                <div class="sm:grid sm:grid-cols-12 sm:items-start sm:gap-4 sm:py-3">
                    <label class="block font-medium leading-6 text-gray-700 py-4 flex-shrink dark:text-gray-200 sm:pt-1.5">{{ __('Post Tags') }}</label>
                    <div class="mt-2 sm:col-span-11 sm:mt-0">
                        <tag-search post-id="{{ $post->ulid }}" class="block w-full max-w-6xl dark:invert"></tag-search>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/posts/index.blade.php
<x-app-layout>
    @seoTitle(__('Blog Posts'))
    <x-slot name="header">
        <div class="flex justify-between items-center">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight dark:text-gray-200">
                {{ __('Blog Posts') }}
            </h2>
            <Link href="{{ route('posts.create') }}" type="button" class="inline-flex items-center rounded-md bg-green-500 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-green-400">
                <span class="antd icon-plus"></span>
                <span class="pl-1">{{ __('Create Post') }}</span>
            </Link>
        </div>
    </x-slot>

    <div class="py-10">
        <div class="max-w-7xl mx-auto px-4">
            @foreach ($posts as $post)
                <div class="lg:flex lg:items-center lg:justify-between bg-white bg-opacity-50 overflow-hidden shadow-sm sm:rounded-lg dark:bg-zinc-900 dark:bg-opacity-50 px-4 py-4 transform hover:scale-105 transition duration-300 mb-5 backdrop-blur-sm backdrop-filter">
                    <div class="min-w-0 flex-1">
                        <h2 class="leading-7 text-gray-800 sm:truncate sm:text-2xl sm:tracking-wider dark:text-gray-200"><span class="antd icon-biaoti text-2xl mr-2"></span>{{ $post->title }}</h2>
                        <div class="mt-1 flex flex-col sm:mt-0 sm:flex-row sm:flex-wrap sm:space-x-6">
                            <div class="mt-2 flex items-center text-sm text-gray-600 dark:text-gray-300">
                                <span class="antd icon-time-circle-fill"><span class="pl-1 {{ $FONT_FAMILY }}">{{ $post->created_at->format('Y-m-d h:m:s') }}</span></span>
                            </div>
                            <div class="mt-2 flex items-center text-sm text-gray-600 dark:text-gray-300">
                                <span class="antd icon-folder-open-fill"><span class="pl-1 {{ $FONT_FAMILY }}">{{ $post->category->title }}</span></span>
                            </div>
                        </div>
                    </div>
                    <div class="mt-5 flex lg:ml-4 lg:mt-0">
                        <span>
                          <Link href="{{ route('posts.edit', $post) }}" type="button" class="inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-700 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 dark:bg-zinc-700 dark:ring-zinc-700 dark:hover:bg-zinc-900 dark:text-gray-200">
                              <span class="antd icon-edit-fill"></span>
                              <span class="pl-1">{{ __('Edit') }}</span>
                          </Link>
                        </span>

                        <span class="lg:ml-3 ml-1">
                          <a href="{{ route('posts.show', $post) }}" target="_blank" type="button" class="inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-700 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 dark:bg-zinc-700 dark:ring-zinc-700 dark:hover:bg-zinc-900 dark:text-gray-200">
                            <span class="antd icon-eye-fill"></span>
                            <span class="pl-1">{{ __('View') }}</span>
                          </a>
                        </span>

                        <span class="lg:ml-3 ml-1">
                          <Link href="{{ route('posts.comments', $post) }}" type="button" class="inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-700 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 dark:bg-zinc-700 dark:ring-zinc-700 dark:hover:bg-zinc-900 dark:text-gray-200">
                            <span class="antd icon-comment-fill"></span>
                            <span class="pl-1">{{ __('Comment Management') }}</span>
                          </Link>
                        </span>

                        <span class="lg:ml-3 ml-1">
                            <div x-data="{
                              published: {{ $post->published }},
                              toggle() {
                                this.published = !this.published;
                                axios.patch('{{ route('posts.update', $post) }}', {
                                  published: this.published
                                });
                              },
                              publishedStatus() {
                                return this.published ? `&nbsp;{{ __('Unpublish') }}` : `&nbsp;{{ __('Publish') }}`;
                              }
                            }">
                                <button x-on:click="toggle()"
                                        class="inline-flex items-center rounded-md bg-green-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-green-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600"
                                        x-bind:class="{ 'bg-orange-500 hover:bg-orange-400': published }">
                                    <span class="antd icon-publish" x-bind:class="{ 'icon-unpublish': published }"></span>
                                    <span class="pl-1" x-text="publishedStatus()"></span>
                                </button>
                            </div>
                        </span>

                        <span class="lg:ml-3 ml-1">
                            <Link href="{{ route('posts.destroy', $post) }}" method="delete" confirm="{{ __('Dangerous operation, confirm to continue?') }}" confirm-text="{{ trans('post.deletePostConfirm', ['title' => $post->title]) }}"
                                  confirm-button="{{ __('Delete Post') }}" type="button" class="inline-flex items-center rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-600">
                            <span class="antd icon-delete-fill"></span>
                            <span class="pl-1">{{ __('Delete') }}</span>
                          </Link>
                        </span>

                    </div>
                </div>

            @endforeach
            <div class="mt-5">
                {{ $posts->links() }}
            </div>
        </div>
    </div>
</x-app-layout>