routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::any('wechat', [\App\Http\Controllers\WeChatController::class, 'serve']);
Route::get('/wechat/qrcode', 'App\Http\Controllers\WeChatController@getQRCode');
Route::any('/wechat/upload', 'App\Http\Controllers\WeChatController@upload');
Route::any('/wechat/alist', 'App\Http\Controllers\WeChatController@alist');
Route::any('/wechat/draft', 'App\Http\Controllers\WeChatController@draft');
Route::any('/wechat/publish', 'App\Http\Controllers\WeChatController@publish');

Route::middleware('splade')->group(function () {
    Route::spladeWithVueBridge();
    Route::spladePasswordConfirmation();
    Route::spladeTable();
    Route::spladeUploads();

    Route::middleware(['auth', 'master', 'verified'])->group(function () {
        Route::get('/dashboard', 'App\Http\Controllers\DashboardController@index')->name('dashboard.index');
        Route::patch('/dashboard', 'App\Http\Controllers\DashboardController@update')->name('dashboard.update');
        Route::get('/dashboard/setting', 'App\Http\Controllers\DashboardController@setting')->name('dashboard.setting');
        Route::get('/dashboard/storage', 'App\Http\Controllers\DashboardController@storage')->name('dashboard.storage');
        Route::get('/dashboard/socialite', 'App\Http\Controllers\DashboardController@socialite')->name('dashboard.socialite');
        Route::get('/dashboard/master', 'App\Http\Controllers\DashboardController@master')->name('dashboard.master');
        Route::get('/dashboard/mail', 'App\Http\Controllers\DashboardController@mail')->name('dashboard.mail');
        Route::get('/dashboard/secure', 'App\Http\Controllers\DashboardController@secure')->name('dashboard.secure');
        Route::get('/dashboard/scout', 'App\Http\Controllers\DashboardController@scout')->name('dashboard.scout');
        Route::get('/dashboard/background/image', 'App\Http\Controllers\DashboardController@bgImage')->name('dashboard.background.image');
        Route::get('/dashboard/background/video', 'App\Http\Controllers\DashboardController@bgVideo')->name('dashboard.background.video');

        Route::resource('posts', \App\Http\Controllers\PostController::class)->except(['show']);
        Route::resource('categories', \App\Http\Controllers\CategoryController::class)->except(['show']);
        Route::get('/tags', 'App\Http\Controllers\TagController@index')->name('tags.index');
        Route::get('/tags/search', 'App\Http\Controllers\TagController@search')->name('tags.search');
        Route::post('/tags', 'App\Http\Controllers\TagController@store')->name('tags.store');
        Route::post('/posts/{post}/tags', 'App\Http\Controllers\TagController@createPostsTag')->name('posts.tags.store');
        Route::get('/posts/{post}/tags', 'App\Http\Controllers\TagController@getPostsTag')->name('posts.tags.index');
        Route::delete('/posts/{post}/tags', 'App\Http\Controllers\TagController@destroyPostsTag')->name('posts.tags.destroy');
        Route::resource('users', \App\Http\Controllers\UserController::class);
        Route::resource('comments', \App\Http\Controllers\CommentController::class)->except(['store']);
        Route::get('/posts/{post}/comments', 'App\Http\Controllers\PostController@comment')->name('posts.comments');
    });

    Route::middleware('uvcount')->group(function () {
        Route::get('/', 'App\Http\Controllers\HomeController@index')->name('home');
        Route::get('/tag/{name?}', 'App\Http\Controllers\HomeController@tag')->name('tag');
        Route::get('/timeline/{yearMonth?}', 'App\Http\Controllers\HomeController@timeline')
            ->where('yearMonth', '(20\d{2}(0[1-9]|1[0-2])|\d{4}(0?[1-9]|1[0-2]))')
            ->name('timeline');
        Route::get('/getPostsByDate/{date}', 'App\Http\Controllers\HomeController@getPostsByDate')->name('getPostsByDate');
        Route::get('/posts/{post:slug}', 'App\Http\Controllers\PostController@show')->name('posts.show');
        Route::get('/categories/{category:slug}', 'App\Http\Controllers\CategoryController@show')->name('categories.show');
        Route::get('/search', 'App\Http\Controllers\HomeController@search')->name('search');
        Route::post('/search', 'App\Http\Controllers\HomeController@searchResult')->name('search.result');
        Route::get('/comments/post/{post:ulid}', 'App\Http\Controllers\CommentController@post')->name('comments.post');
        Route::get('/is_login', function () {
            if (auth()->check()) {
                return response()->json(['code' => 200, 'data' => auth()->user()]);
            } else {
                return response()->json(['code' => 401, 'message' => 'Unauthorized.']);
            }
        });
    });

    Route::middleware(['auth', 'verified'])->group(function () {
        Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
        Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
        Route::post('/comments', 'App\Http\Controllers\CommentController@store')->name('comments.store');
        Route::post('/upload/video', 'App\Http\Controllers\UploadController@video')->name('upload.video');
        Route::post('/upload/image', 'App\Http\Controllers\UploadController@image')->name('upload.image');
        Route::post('/upload/file', 'App\Http\Controllers\UploadController@file')->name('upload.file');
        Route::post('/upload/check_exists', 'App\Http\Controllers\UploadController@checkExists')->name('upload.check_exists');
    });

    Route::get('/install', 'App\Http\Controllers\InstallController@index')->name('install.index');
    Route::get('/install/settings/{locale}', 'App\Http\Controllers\InstallController@settings')->name('install.settings');
    Route::post('/install/check/{locale}', 'App\Http\Controllers\InstallController@check')->name('install.check');
    Route::get('/install/create/{locale}', 'App\Http\Controllers\InstallController@create')->name('install.create');
    Route::post('/install/install/{locale}', 'App\Http\Controllers\InstallController@install')->name('install.install');
    Route::get('/install/finish/{locale}', 'App\Http\Controllers\InstallController@finish')->name('install.finish');
    Route::get('/select-locale/{locale}', function ($locale) {
        \Illuminate\Support\Facades\Session::put('locale', $locale);
        return redirect()->back();
    })->name('select-locale');

    require __DIR__.'/auth.php';
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Kalnoy\Nestedset\NodeTrait;

class Category extends Model
{
    use HasFactory;
    use NodeTrait;

    protected $fillable = [
        'title',
        'parent_id',
        'slug',
        'description'
    ];

    protected function serializeDate(\DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function children()
    {
        return $this->hasMany(Category::class, 'parent_id');
    }

    public function parent()
    {
        return $this->belongsTo(Category::class, 'parent_id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreCategoryRequest;
use App\Http\Requests\UpdateCategoryRequest;
use App\Models\Category;
use App\Services\CategoryService;
use App\Services\PostService;
use Illuminate\Support\Facades\Redirect;
use ProtoneMedia\Splade\Facades\SEO;
use ProtoneMedia\Splade\Facades\Toast;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $categories = Category::defaultOrder()->get()->toTree();
        return view('categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $categoryList = Category::defaultOrder()->get()->toTree();
        $categories = CategoryService::getTreeCategories($categoryList, 0);
        return view('categories.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreCategoryRequest $request)
    {
        $category = new Category();
        $category->fill($request->all());
        $category->save();
        Toast::success(trans('Category created successfully!'))->autoDismiss(5);
        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Category $category)
    {
        //获取栏目极其子栏目下所有文章
        $category = Category::with('children', 'parent')->find($category->id);
        $category->posts_count = PostService::getAllPublishedPostsCountsForCategoryAndChildren($category);
        $posts = PostService::getAllPublishedPostsForCategoryAndChildren($category, 9);
        SEO::openGraphType('category');
        SEO::openGraphUrl(config('app.url').'/categories/'.$category->slug);
        SEO::openGraphTitle($category->title.' - '.config('splade-seo.title_suffix'));
        SEO::metaByProperty('og:description', $category->description);
        return view('categories.show', compact('posts', 'posts'), compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Category $category)
    {
        $categoryList = Category::defaultOrder()->get()->toTree();
        $categories = CategoryService::getTreeCategories($categoryList, 0);
        return view('categories.edit', compact('category', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateCategoryRequest $request, Category $category)
    {
        $category->fill($request->all());
        $category->save();
        Toast::success(trans('Category updated successfully!'))->autoDismiss(5);
        return Redirect::route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Category $category)
    {
        $category->delete();
        Toast::success(trans('Category deleted successfully!'))->autoDismiss(5);
        return redirect()->route('categories.index');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/categories/create.blade.php
<x-app-layout>
    @seoTitle(__('Create Category'))
    <x-slot name="header">
        <div class="flex justify-between items-center">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight dark:text-gray-200">
                {{ __('Create Category') }}
            </h2>
        </div>
    </x-slot>

    <div class="py-10">
        <div class="max-w-7xl mx-auto px-4">
            <div class="px-6 py-6 bg-opacity-50 text-gray-800 shadow-sm rounded-lg sm:rounded-lg bg-white dark:bg-zinc-800 dark:bg-opacity-50 backdrop-blur-sm backdrop-filter">
                <x-splade-form action="{{ route('categories.store') }}" class="space-y-4">
                    <span class="block mb-1 text-gray-700 dark:text-gray-200">{{ __('Category Name') }}</span>
                    <x-splade-input id="title" type="text" name="title" placeholder="{{ __('Please enter category name') }}" required autofocus />
                    <span class="block mb-1 text-gray-700 dark:text-gray-200">{{ __('Category Slug') }}</span>
                    <x-splade-input id="slug" type="text" name="slug"  placeholder="{{ __('Please enter category slug') }}" required autocomplete="current-password" />
                    <span class="block mb-1 text-gray-700 dark:text-gray-200">{{ __('Category Description') }}</span>
                    <x-splade-textarea id="description" name="description" placeholder="{{ __('Please enter category description') }}" required />
                    <span class="block mb-1 text-gray-700 dark:text-gray-200">{{ __('Category Parent') }}</span>
                    <x-splade-select id="parent_id" name="parent_id" :options="$categories" option-label="title" option-value="id" />
                    <div class="w-full">
                        <x-splade-submit class="w-full" label="{{ __('Create Category') }}" />
                    </div>
                </x-splade-form>
            </div>
        </div>
    </div>

</x-app-layout>

resources/views/categories/edit.blade.php
<x-app-layout>
    @seoTitle(__('Edit Category'))
    <x-slot name="header">
        <div class="flex justify-between items-center">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight dark:text-gray-200">
                {{ __('Edit Category') }}
            </h2>
        </div>
    </x-slot>

    <div class="py-10">
        <div class="max-w-7xl mx-auto px-4">
            <div class="px-6 py-6 bg-opacity-50 text-gray-800 shadow-sm rounded-lg sm:rounded-lg bg-white dark:bg-zinc-800 dark:bg-opacity-50 backdrop-blur-sm backdrop-filter">
                <x-splade-form :method="'patch'" action="{{ route('categories.update', $category) }}"  :default="$category" class="space-y-4">
                    <span class="block mb-1 text-gray-700 dark:text-gray-200">{{ __('Category Name') }}</span>
                    <x-splade-input id="title" type="text" name="title" placeholder="{{ __('Please enter category name') }}" required autofocus />
                    <span class="block mb-1 text-gray-700 dark:text-gray-200">{{ __('Category Slug') }}</span>
                    <x-splade-input id="slug" type="text" name="slug"  placeholder="{{ __('Please enter category slug') }}" required autocomplete="current-password" />
                    <span class="block mb-1 text-gray-700 dark:text-gray-200">{{ __('Category Description') }}</span>
                    <x-splade-textarea id="description" name="description" placeholder="{{ __('Please enter category description') }}" required />
                    <span class="block mb-1 text-gray-700 dark:text-gray-200">{{ __('Category Parent') }}</span>
                    <x-splade-select id="parent_id" name="parent_id" :options="$categories" option-label="title" option-value="id" />
                    <div class="w-full">
                        <x-splade-submit class="w-full" label="{{ __('Save Category') }}" />
                    </div>
                </x-splade-form>
            </div>
        </div>
    </div>

</x-app-layout>

resources/views/categories/index.blade.php
<x-app-layout>
    @seoTitle(__('Category'))
    <x-slot name="header">
        <div class="flex justify-between items-center">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight dark:text-gray-200">
                {{ __('Category') }}
            </h2>
            <Link href="{{ route('categories.create') }}" type="button" class="inline-flex items-center rounded-md bg-green-500 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-green-400">
                <span class="antd icon-plus"></span>
                <span class="pl-1">{{ __('Create Category') }}</span>
            </Link>
        </div>
    </x-slot>

    <div class="py-10">
        <div class="max-w-7xl mx-auto px-4">
            <div class="px-6 py-1 bg-opacity-50 text-gray-600 shadow-sm rounded-lg sm:rounded-lg bg-white dark:bg-zinc-800 dark:bg-opacity-50 dark:text-gray-200 backdrop-blur-sm backdrop-filter">
                <x-category-list :categories="$categories"></x-category-list>
            </div>
        </div>
    </div>

</x-app-layout>

resources/views/categories/show.blade.php
<x-layout>
    @seoTitle($category->title)
    @seoDescription($category->description)
    <div class="py-24 sm:py-32">
        <div class="mx-auto max-w-7xl px-4">
            <div class="mx-auto max-w-2xl text-center">
                <h2 class="{{ $FONT_FAMILY }} text-3xl font-bold tracking-wider text-white sm:text-5xl" style="text-shadow: rgb(0, 0, 0) 0px 0px 0.8em, rgb(0, 0, 0) 0px 0px 0.4em;">{{ $category->title }}</h2>
            </div>
            <div>
                <div class="hidden sm:block mt-8">
                    <div class="">
                        <nav class="-mb-px flex space-x-8 items-center justify-center" aria-label="Tabs" style="text-shadow: rgb(0, 0, 0) 0px 0px 0.8em, rgb(0, 0, 0) 0px 0px 0.4em;">
                            <Link href="#" class="text-gray-100 hover:border-gray-200 hover:text-gray-300 flex whitespace-nowrap border-b-2 py-4 px-1 text-base font-medium">
                                All
                                <span class="bg-gray-100 text-gray-900 ml-3 hidden rounded-full py-1 px-2.5 text-xs font-medium md:inline-block">{{ $category->posts_count }}</span>
                            </Link>
                            @if($category->parent)
                                <Link href="{{ route('categories.show', $category->parent) }}" class="border-transparent text-gray-100 hover:border-gray-200 hover:text-gray-300 flex whitespace-nowrap border-b-2 py-4 px-1 text-base font-medium">
                                    <span class="transform hover:scale-110 transition duration-300">{{ $category->parent->title }}</span>
                                </Link>
                            @endif
                           @foreach($category->children as $child)
                                <Link href="{{ route('categories.show', $child) }}" class="border-transparent text-gray-100 hover:border-gray-200 hover:text-gray-300 flex whitespace-nowrap border-b-2 py-4 px-1 text-base font-medium">
                                    <span class="transform hover:scale-110 transition duration-300">{{ $child->title }}</span>
                                </Link>
                           @endforeach
                        </nav>
                    </div>
                </div>
            </div>

            @if($posts->isEmpty())
                    <div class="border border-gray-100 bg-white bg-opacity-75 dark:bg-zinc-900 dark:bg-opacity-75 rounded-2xl dark:border-gray-700 text-center pb-12 mt-16">
                        <x-empty tipsText="{{ __('The blogger is preparing high-quality content, please wait patiently...') }}" />
                    </div>
            @else
                <div class="mx-auto mt-16 grid max-w-2xl auto-rows-fr grid-cols-1 gap-8 sm:mt-20 lg:mx-0 lg:max-w-none lg:grid-cols-3">
                    @foreach ($posts as $post)
                        <article class="relative isolate flex flex-col justify-end overflow-hidden rounded-2xl bg-gray-100 bg-opacity-80 dark:bg-zinc-700 dark:bg-opacity-80 px-8 pb-8 pt-80 sm:pt-48 lg:pt-80">
                            <img src="{{ $post->image }}" alt="" class="absolute inset-0 -z-10 h-full w-full object-cover">
                            <div class="absolute inset-0 -z-10 bg-gradient-to-t from-gray-100 via-gray-100/40 dark:from-gray-900 dark:via-gray-900/40"></div>
                            <div class="absolute inset-0 -z-10 rounded-2xl ring-1 ring-inset ring-gray-100/10 dark:ring-gray-900/10"></div>

                            <div class="flex flex-wrap items-center gap-y-1 overflow-hidden text-sm leading-6 text-gray-600 dark:text-gray-300">
                                <time datetime="{{ $post->published_at }}" class="mr-8">{{ $post->published_at->format('Y'.'年'.'m'.'月'.'d'.'日'.' H:i') }}</time>
                            </div>
                            <h3 class="mt-3 text-lg font-semibold leading-6 text-black dark:text-white">
                                <Link href="{{ route('posts.show', $post) }}">
                                    <span class="absolute inset-0"></span>
                                    {{ $post->title }}
                                </Link>
                            </h3>
                        </article>
                    @endforeach
                    <!-- More posts... -->
                </div>
                <div class="mt-5">
                    {{ $posts->links() }}
                </div>
            @endif
        </div>
    </div>
</x-layout>