routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::any('wechat', [\App\Http\Controllers\WeChatController::class, 'serve']);
Route::get('/wechat/qrcode', 'App\Http\Controllers\WeChatController@getQRCode');
Route::any('/wechat/upload', 'App\Http\Controllers\WeChatController@upload');
Route::any('/wechat/alist', 'App\Http\Controllers\WeChatController@alist');
Route::any('/wechat/draft', 'App\Http\Controllers\WeChatController@draft');
Route::any('/wechat/publish', 'App\Http\Controllers\WeChatController@publish');

Route::middleware('splade')->group(function () {
    Route::spladeWithVueBridge();
    Route::spladePasswordConfirmation();
    Route::spladeTable();
    Route::spladeUploads();

    Route::middleware(['auth', 'master', 'verified'])->group(function () {
        Route::get('/dashboard', 'App\Http\Controllers\DashboardController@index')->name('dashboard.index');
        Route::patch('/dashboard', 'App\Http\Controllers\DashboardController@update')->name('dashboard.update');
        Route::get('/dashboard/setting', 'App\Http\Controllers\DashboardController@setting')->name('dashboard.setting');
        Route::get('/dashboard/storage', 'App\Http\Controllers\DashboardController@storage')->name('dashboard.storage');
        Route::get('/dashboard/socialite', 'App\Http\Controllers\DashboardController@socialite')->name('dashboard.socialite');
        Route::get('/dashboard/master', 'App\Http\Controllers\DashboardController@master')->name('dashboard.master');
        Route::get('/dashboard/mail', 'App\Http\Controllers\DashboardController@mail')->name('dashboard.mail');
        Route::get('/dashboard/secure', 'App\Http\Controllers\DashboardController@secure')->name('dashboard.secure');
        Route::get('/dashboard/scout', 'App\Http\Controllers\DashboardController@scout')->name('dashboard.scout');
        Route::get('/dashboard/background/image', 'App\Http\Controllers\DashboardController@bgImage')->name('dashboard.background.image');
        Route::get('/dashboard/background/video', 'App\Http\Controllers\DashboardController@bgVideo')->name('dashboard.background.video');

        Route::resource('posts', \App\Http\Controllers\PostController::class)->except(['show']);
        Route::resource('categories', \App\Http\Controllers\CategoryController::class)->except(['show']);
        Route::get('/tags', 'App\Http\Controllers\TagController@index')->name('tags.index');
        Route::get('/tags/search', 'App\Http\Controllers\TagController@search')->name('tags.search');
        Route::post('/tags', 'App\Http\Controllers\TagController@store')->name('tags.store');
        Route::post('/posts/{post}/tags', 'App\Http\Controllers\TagController@createPostsTag')->name('posts.tags.store');
        Route::get('/posts/{post}/tags', 'App\Http\Controllers\TagController@getPostsTag')->name('posts.tags.index');
        Route::delete('/posts/{post}/tags', 'App\Http\Controllers\TagController@destroyPostsTag')->name('posts.tags.destroy');
        Route::resource('users', \App\Http\Controllers\UserController::class);
        Route::resource('comments', \App\Http\Controllers\CommentController::class)->except(['store']);
        Route::get('/posts/{post}/comments', 'App\Http\Controllers\PostController@comment')->name('posts.comments');
    });

    Route::middleware('uvcount')->group(function () {
        Route::get('/', 'App\Http\Controllers\HomeController@index')->name('home');
        Route::get('/tag/{name?}', 'App\Http\Controllers\HomeController@tag')->name('tag');
        Route::get('/timeline/{yearMonth?}', 'App\Http\Controllers\HomeController@timeline')
            ->where('yearMonth', '(20\d{2}(0[1-9]|1[0-2])|\d{4}(0?[1-9]|1[0-2]))')
            ->name('timeline');
        Route::get('/getPostsByDate/{date}', 'App\Http\Controllers\HomeController@getPostsByDate')->name('getPostsByDate');
        Route::get('/posts/{post:slug}', 'App\Http\Controllers\PostController@show')->name('posts.show');
        Route::get('/categories/{category:slug}', 'App\Http\Controllers\CategoryController@show')->name('categories.show');
        Route::get('/search', 'App\Http\Controllers\HomeController@search')->name('search');
        Route::post('/search', 'App\Http\Controllers\HomeController@searchResult')->name('search.result');
        Route::get('/comments/post/{post:ulid}', 'App\Http\Controllers\CommentController@post')->name('comments.post');
        Route::get('/is_login', function () {
            if (auth()->check()) {
                return response()->json(['code' => 200, 'data' => auth()->user()]);
            } else {
                return response()->json(['code' => 401, 'message' => 'Unauthorized.']);
            }
        });
    });

    Route::middleware(['auth', 'verified'])->group(function () {
        Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
        Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
        Route::post('/comments', 'App\Http\Controllers\CommentController@store')->name('comments.store');
        Route::post('/upload/video', 'App\Http\Controllers\UploadController@video')->name('upload.video');
        Route::post('/upload/image', 'App\Http\Controllers\UploadController@image')->name('upload.image');
        Route::post('/upload/file', 'App\Http\Controllers\UploadController@file')->name('upload.file');
        Route::post('/upload/check_exists', 'App\Http\Controllers\UploadController@checkExists')->name('upload.check_exists');
    });

    Route::get('/install', 'App\Http\Controllers\InstallController@index')->name('install.index');
    Route::get('/install/settings/{locale}', 'App\Http\Controllers\InstallController@settings')->name('install.settings');
    Route::post('/install/check/{locale}', 'App\Http\Controllers\InstallController@check')->name('install.check');
    Route::get('/install/create/{locale}', 'App\Http\Controllers\InstallController@create')->name('install.create');
    Route::post('/install/install/{locale}', 'App\Http\Controllers\InstallController@install')->name('install.install');
    Route::get('/install/finish/{locale}', 'App\Http\Controllers\InstallController@finish')->name('install.finish');
    Route::get('/select-locale/{locale}', function ($locale) {
        \Illuminate\Support\Facades\Session::put('locale', $locale);
        return redirect()->back();
    })->name('select-locale');

    require __DIR__.'/auth.php';
});

resources/views/layouts/app.blade.php
@if($BACKGROUND_TYPE == 'image')
    <div class="fixed top-0 left-0 w-full h-full z-[-100]">
        <div class="object-cover w-full h-full" style="background-image: url({{ $BACKGROUND_IMAGE }});background-size: cover;"></div>
        <div class="bg-gray-100 bg-opacity-25 absolute top-0 left-0 w-full h-full dark:bg-zinc-900 dark:bg-opacity-25"></div>
    </div>
@elseif($BACKGROUND_TYPE == 'video')
    <div class="fixed top-0 left-0 w-full h-full z-[-100]">
        <video autoplay muted loop class="object-cover w-full h-full" style="object-fit: cover;">
            <source src="{{ $BACKGROUND_IMAGE }}" type="video/mp4">
            Your browser does not support the video tag.
        </video>
        <div class="bg-gray-100 bg-opacity-25 absolute top-0 left-0 w-full h-full dark:bg-zinc-900 dark:bg-opacity-25"></div>
    </div>
@endif
<div class="flex flex-col flex-grow z-0 mx-auto {{ $FONT_FAMILY }}">

    @if(auth()->user()->id == 1)
        @include('layouts.navigation')
        <main class="flex-1 overflow-y-auto mt-36">
            {{ $slot }}
        </main>
    @else
        @include('components.navigation')
        <main class="flex-1 overflow-y-auto mt-12">
            {{ $slot }}
        </main>
    @endif
    <Footer app-name="{{ env('APP_NAME') }}" icp-number="{{ env('ICP_NUMBER') }}" all-rights-reserved="{!! trans('All Rights Reserved') !!}" />
</div>

resources/views/layouts/guest.blade.php
@if($BACKGROUND_TYPE == 'image')
    <div class="fixed top-0 left-0 w-full h-full z-[-100]">
        <div class="object-cover w-full h-full" style="background-image: url({{ $BACKGROUND_IMAGE }});background-size: cover;"></div>
        <div class="bg-gray-100 bg-opacity-25 absolute top-0 left-0 w-full h-full dark:bg-zinc-900 dark:bg-opacity-25"></div>
    </div>
@elseif($BACKGROUND_TYPE == 'video')
    <div class="fixed top-0 left-0 w-full h-full z-[-100]">
        <video autoplay muted loop class="object-cover w-full h-full" style="object-fit: cover;">
            <source src="{{ $BACKGROUND_IMAGE }}" type="video/mp4">
            Your browser does not support the video tag.
        </video>
        <div class="bg-gray-100 bg-opacity-25 absolute top-0 left-0 w-full h-full dark:bg-zinc-900 dark:bg-opacity-25"></div>
    </div>
@endif
<div class="text-gray-900 antialiased {{ $FONT_FAMILY }}">
    {{ $slot }}
</div>

resources/views/layouts/navigation.blade.php
<x-splade-toggle>
    <div id="navigation" class="fixed top-0 w-full bg-white bg-opacity-50 dark:bg-zinc-900 dark:bg-opacity-50 z-10 backdrop-blur-sm backdrop-filter">
        <nav class="w-full border-b border-gray-200 dark:border-zinc-700">
            <!-- Primary Navigation Menu -->
            <div class="max-w-7xl mx-auto px-4">
                <div class="flex justify-between h-16">
                    <div class="flex">
                        <!-- Logo -->
                        <div class="shrink-0 flex items-center transform hover:scale-125 transition duration-300">
                            <Link href="{{ route('home') }}">
                                <SvgLogo url="{{ env('APP_LOGO') }}" font-size="text-3xl" height="h-9" site-name="{{ env('APP_NAME') }}" align="left" />
                            </Link>
                        </div>

                        <!-- Navigation Links -->
                        <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                            <x-nav-link :href="route('dashboard.index')" :active="request()->routeIs('dashboard.index')">
                                <span class="antd icon-dashboard-fill"><span class="ml-2 {{ $FONT_FAMILY }}">{{ __('Dashboard') }}</span></span>
                            </x-nav-link>
                        </div>
                        <div class="hidden space-x-8 sm:-my-px sm:ml-5 sm:flex">
                            <x-nav-link :href="route('categories.index')" :active="request()->routeIs('categories.index')">
                                <span class="antd icon-folder-fill"><span class="ml-2 {{ $FONT_FAMILY }}">{{ __('Category') }}</span></span>
                            </x-nav-link>
                        </div>
                        <div class="hidden space-x-8 sm:-my-px sm:ml-5 sm:flex">
                            <x-nav-link :href="route('posts.index')" :active="request()->routeIs('posts.index')">
                                <span class="antd icon-article-fill"><span class="ml-2 {{ $FONT_FAMILY }}">{{ __('Blog Posts') }}</span></span>
                            </x-nav-link>
                        </div>
                        <div class="hidden space-x-8 sm:-my-px sm:ml-5 sm:flex">
                            <x-nav-link :href="route('users.index')" :active="request()->routeIs('users.index')">
                                <span class="antd icon-yonghuguanli"><span class="ml-2 {{ $FONT_FAMILY }}">{{ __('Users Management') }}</span></span>
                            </x-nav-link>
                        </div>
                        <div class="hidden space-x-8 sm:-my-px sm:ml-5 sm:flex">
                            <x-nav-link :href="route('comments.index')" :active="request()->routeIs('comments.index')">
                                <span class="antd icon-comment-fill"><span class="ml-2 {{ $FONT_FAMILY }}">{{ __('Comment Management') }}</span></span>
                            </x-nav-link>
                        </div>
                        <div class="hidden space-x-8 sm:-my-px sm:ml-5 sm:flex">
                            <x-nav-link :href="route('dashboard.setting')" :active="request()->routeIs('dashboard.setting')">
                                <span class="antd icon-setting-fill"><span class="ml-2 {{ $FONT_FAMILY }}">{{ __('System Settings') }}</span></span>
                            </x-nav-link>
                        </div>
                    </div>

                    <!-- Settings Dropdown -->
                    <div class="hidden sm:flex sm:items-center sm:ml-6">
                        @auth
                            <x-dropdown width="24" placement="bottom-end">
                                <x-slot name="trigger">
                                    <button class="flex items-center text-sm font-medium text-gray-900 hover:text-gray-700 focus:outline-none transition duration-150 ease-in-out dark:text-gray-200 dark:hover:text-gray-400">
                                        <div class="{{ $FONT_FAMILY }} text-base">{{ Auth::user()->name }}</div>

                                        <div class="ml-1">
                                            <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                                <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                            </svg>
                                        </div>
                                    </button>
                                </x-slot>

                                <x-slot name="content">
                                    @if(Auth::user()->id == 1)
                                        <x-dropdown-link :href="route('dashboard.index')">
                                            {{ __('Dashboard') }}
                                        </x-dropdown-link>

                                    @endif
                                    <x-dropdown-link :href="route('profile.edit')">
                                        {{ __('Profile') }}
                                    </x-dropdown-link>

                                    <!-- Authentication -->
                                    <form method="POST" action="{{ route('logout') }}">
                                        @csrf

                                        <x-dropdown-link as="a" :href="route('logout')" onclick="event.preventDefault(); this.closest('form').submit();">
                                            {{ __('Log Out') }}
                                        </x-dropdown-link>
                                    </form>
                                </x-slot>
                            </x-dropdown>
                        @else
                            <Link href="{{ route('login') }}" class="{{ $FONT_FAMILY }} text-gray-900 dark:text-gray-200 dark:hover:text-gray-100">{{ __('Log in') }}</Link>

                            @if (Route::has('register'))
                                <Link href="{{ route('register') }}" class="{{ $FONT_FAMILY }} ml-4 text-gray-900 dark:text-gray-200 dark:hover:text-gray-100">{{ __('Register') }}</Link>
                            @endif
                        @endauth
                        <ThemeSwitch class="ml-5 pt-1" />
                    </div>

                    <!-- Hamburger -->
                    <div class="-mr-2 flex items-center sm:hidden">
                        <ThemeSwitch class="mr-2 pt-1" />
                        <button @click="toggle" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                            <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                                <path v-bind:class="{ hidden: toggled, 'inline-flex': !toggled }" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                                <path v-bind:class="{ hidden: !toggled, 'inline-flex': toggled }" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                            </svg>
                        </button>
                    </div>
                </div>
            </div>

            <!-- Responsive Navigation Menu -->
            <div v-bind:class="{ block: toggled, hidden: !toggled }" class="sm:hidden">
                <div class="pt-2 pb-3 space-y-1 {{ $FONT_FAMILY }}">
                    <x-responsive-nav-link :href="route('dashboard.index')" :active="request()->routeIs('dashboard.index')">
                        <span class="antd icon-dashboard-fill"><span class="ml-2 {{ $FONT_FAMILY }}">{{ __('Dashboard') }}</span></span>
                    </x-responsive-nav-link>
                    <x-responsive-nav-link :href="route('categories.index')" :active="request()->routeIs('categories.index')">
                        <span class="antd icon-folder-fill"><span class="ml-2 {{ $FONT_FAMILY }}">{{ __('Category') }}</span></span>
                    </x-responsive-nav-link>
                    <x-responsive-nav-link :href="route('posts.index')" :active="request()->routeIs('posts.index')">
                        <span class="antd icon-article-fill"><span class="ml-2 {{ $FONT_FAMILY }}">{{ __('Blog Posts') }}</span></span>
                    </x-responsive-nav-link>
                </div>

                <!-- Responsive Settings Options -->
                <div class="pt-4 pb-1 border-t border-gray-200 px-4 {{ $FONT_FAMILY }}">
                    @auth
                        <div class="px-2">
                            <div class="font-medium text-base text-gray-800 dark:text-gray-200">{{ Auth::user()->name }}</div>
                            <div class="font-medium text-sm text-gray-500 dark:text-gray-300">{{ Auth::user()->email }}</div>
                        </div>

                        <div class="mt-3 space-y-1">
                            <x-responsive-nav-link :href="route('profile.edit')">
                                {{ __('Profile') }}
                            </x-responsive-nav-link>

                            <!-- Authentication -->
                            <form method="POST" action="{{ route('logout') }}">
                                @csrf

                                <x-responsive-nav-link as="a" :href="route('logout')" onclick="event.preventDefault(); this.closest('form').submit();">
                                    {{ __('Log Out') }}
                                </x-responsive-nav-link>
                            </form>
                        </div>
                    @else
                        <Link href="{{ route('login') }}" class="text-sm text-gray-700 dark:text-gray-200 ">{{ __('Log in') }}</Link>

                        @if (Route::has('register'))
                            <Link href="{{ route('register') }}" class="ml-4 text-sm text-gray-700 dark:text-gray-200 ">{{ __('Register') }}</Link>
                        @endif
                    @endauth
                </div>
            </div>
        </nav>
        <header>
            <div class="max-w-7xl mx-auto py-6 px-4">
                {{ $header }}
            </div>
        </header>
    </div>
</x-splade-toggle>
<x-splade-script>
    window.addEventListener('scroll', function() {
        var div = document.getElementById('navigation');

        if (window.scrollY > div.offsetHeight / 2) {
            div.classList.remove('backdrop-blur-sm');
            div.classList.add('backdrop-blur-lg');
        } else {
            div.classList.remove('backdrop-blur-lg');
            div.classList.add('backdrop-blur-sm');
        }
    });
</x-splade-script>